#!/bin/bash
#
# God
#
# chkconfig: - 85 15
# description: start, stop, restart, status for God
#
# From: http://www.synbioz.com/blog/monitoring_server_processes_with_god

RETVAL=0

case "$1" in
    start)
      <RVM install dir>/.rvm/bin/bootup_god -P /var/run/god.pid -l /var/log/god.log
      <RVM install dir>/.rvm/bin/bootup_god load /etc/god.conf
      RETVAL=$?
      ;;
    stop)
      kill `cat /var/run/god.pid`
      RETVAL=$?
      ;;
    restart)
      kill `cat /var/run/god.pid`
      <RVM install dir>/.rvm/bin/bootup_god -P /var/run/god.pid -l /var/log/god.log
      <RVM install dir>/.rvm/bin/bootup_god load /etc/god.conf
      RETVAL=$?
      ;;
    status)
      <RVM install dir>/.rvm/bin/bootup_god status
      RETVAL=$?
      ;;
    *)
      echo "Usage: god {start|stop|restart|status}"
      exit 1
  ;;
esac

exit $RETVAL